# Generated by Django 6.0.5 on 2026-05-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Built on Compassion & Excellence', max_length=300)),
                ('title_km', models.CharField(default='បង្កើតឡើងលើចិត្តអាណិត', max_length=300)),
                ('body_en', models.TextField(default="Since 2001, we have been the region's most trusted nursing school.")),
                ('body_km', models.TextField(default='តាំងពីឆ្នាំ ២០០១ យើងជាសាលាដែលទុកចិត្តបានបំផុត។')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('years_label_en', models.CharField(default='Years of Excellence', max_length=100)),
                ('years_label_km', models.CharField(default='ឆ្នាំនៃភាពល្អឥតខ្ចោះ', max_length=100)),
                ('years_number', models.CharField(default='23rd', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('grade_applying', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Get In Touch', max_length=200)),
                ('title_km', models.CharField(default='ទំនាក់ទំនងយើង', max_length=200)),
                ('phone', models.CharField(default='(325) 942-0000', max_length=50)),
                ('email', models.EmailField(default='admissions@school.edu', max_length=254)),
                ('address_en', models.TextField(default='2400 W. Avenue N, San Angelo, TX 76904')),
                ('address_km', models.TextField(default='San Angelo, TX')),
                ('hours_en', models.CharField(default='Mon–Fri 8AM–6PM', max_length=200)),
                ('hours_km', models.CharField(default='ចន្ទ–សុក្រ ៨ព្រឹក–៦ល្ងាច', max_length=200)),
                ('admission_info_en', models.TextField(default='Applications are reviewed on a rolling basis.')),
                ('admission_info_km', models.TextField(default='ពាក្យស្នើសុំត្រូវបានពិនិត្យជានិច្ច។')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_km', models.CharField(max_length=200)),
                ('description_en', models.TextField()),
                ('description_km', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_km', models.CharField(blank=True, max_length=200)),
                ('description_en', models.CharField(blank=True, max_length=300)),
                ('description_km', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('events', 'Events'), ('students', 'Students'), ('facilities', 'Facilities'), ('sports', 'Sports'), ('ceremonies', 'Ceremonies'), ('classroom', 'Classroom')], default='events', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Train to Heal. Lead to Care.', max_length=300)),
                ('title_km', models.CharField(default='រៀនព្យាបាល។ នាំការថែទាំ។', max_length=300)),
                ('subtitle_en', models.TextField(default='We prepare compassionate, skilled nurses.')),
                ('subtitle_km', models.TextField(default='យើងបណ្តុះបណ្តាលគិលានុបដ្ឋាក។')),
                ('badge_en', models.CharField(default='ACEN Accredited · Est. 2001', max_length=200)),
                ('badge_km', models.CharField(default='ទទួលស្គាល់ ACEN · ២០០១', max_length=200)),
                ('btn1_en', models.CharField(default='Apply Now', max_length=100)),
                ('btn1_km', models.CharField(default='ដាក់ពាក្យឥឡូវ', max_length=100)),
                ('btn2_en', models.CharField(default='Contact Admissions', max_length=100)),
                ('btn2_km', models.CharField(default='ទំនាក់ទំនង', max_length=100)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('stat1_num', models.CharField(default='98%', max_length=20)),
                ('stat1_label_en', models.CharField(default='NCLEX Pass Rate', max_length=100)),
                ('stat1_label_km', models.CharField(default='អត្រាប្រឡងជាប់', max_length=100)),
                ('stat2_num', models.CharField(default='2,400+', max_length=20)),
                ('stat2_label_en', models.CharField(default='Graduates', max_length=100)),
                ('stat2_label_km', models.CharField(default='អ្នកបញ្ចប់', max_length=100)),
                ('stat3_num', models.CharField(default='45+', max_length=20)),
                ('stat3_label_en', models.CharField(default='Clinical Partners', max_length=100)),
                ('stat3_label_km', models.CharField(default='ដៃគូ', max_length=100)),
                ('stat4_num', models.CharField(default='94%', max_length=20)),
                ('stat4_label_en', models.CharField(default='Employment Rate', max_length=100)),
                ('stat4_label_km', models.CharField(default='អត្រាការងារ', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Visit Our Campus', max_length=200)),
                ('title_km', models.CharField(default='ចូលទស្សនាសាលា', max_length=200)),
                ('address_en', models.TextField(default='2400 W. Avenue N, San Angelo, TX 76904')),
                ('address_km', models.TextField(default='San Angelo, TX')),
                ('google_map_embed', models.TextField(blank=True)),
                ('open_map_url', models.URLField(blank=True, default='https://maps.google.com')),
                ('hours_en', models.CharField(default='Mon–Fri 8AM–6PM · Sat 9AM–1PM', max_length=200)),
                ('hours_km', models.CharField(default='ចន្ទ–សុក្រ ៨ព្រឹក–៦ល្ងាច', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_km', models.CharField(max_length=200)),
                ('description_en', models.TextField()),
                ('description_km', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('icon', models.CharField(default='🎓', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name_en', models.CharField(default='Apex Nursing College', max_length=200)),
                ('school_name_km', models.CharField(default='មហាវិទ្យាល័យ Apex', max_length=200)),
                ('tagline_en', models.CharField(default='Accredited · Est. 2001', max_length=300)),
                ('tagline_km', models.CharField(default='ទទួលស្គាល់ · ២០០១', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('phone', models.CharField(default='(325) 942-0000', max_length=50)),
                ('email', models.EmailField(default='admissions@school.edu', max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
